### ISSUE TITLE
Can't login

### ISSUE THREAD

**Issue by gbonline** [rbCAS/CASinoApp#1]
Hi, I'm looking for a CAS solution and i tryed this app.
i can run this with
bundle exec rails s
so i try on browser standard port 3000.
I've inserted some simple users in the users table
and when i write username and password on the form fields
i can't login ! 
I've tried the rubycas-server app and all have gone well
What can I do?
Giorgio

**Comment by vmahindra-c** [comment]
hi,
I have problem in login with users which i created in casino_users using mysql2 database. My cas.yml file is:
defaults: &defaults
  login_ticket:
    lifetime: 600
  service_ticket:
    lifetime_unconsumed: 300
    lifetime_consumed: 86400
  proxy_ticket:
    lifetime_unconsumed: 300
    lifetime_consumed: 86400
  frontend:
    sso_name: "CASino"
    footer_text: "Powered by <a href=\"http://rbcas.com/\">CASino</a>"

development:
  <<: *defaults
  authenticators:
       my_company_sql_database:
         authenticator: "ActiveRecord"
         options:
           connection:
             adapter: "mysql2"
             host: "localhost"
             username: "root"
             password: "maheshwari"
             database: "CASinoApp"
           table: "casino_users"
           username_column: "username"
           password_column: "password"
           extra_attributes:
             email: "email_database_column"
             fullname: "displayname_database_column"

test:
  <<: *defaults
  authenticators:
    static:
      class: "CASino::StaticAuthenticator"
      options:
        users:
          testuser:
            password: "foobar123"

production:
  <<: *defaults
  authenticators:
    my_company_ldap:
      authenticator: "LDAP"
      options:
        host: "localhost"
        port: 12445
        base: "dc=users,dc=example.com"
        username_attribute: "uid"
        encryption: "simple_tls"
        extra_attributes:
          email: "mail

and my database.yml is:

development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: CASinoApp
  pool: 5
  username: root
  password: maheshwari
  socket: /var/run/mysqld/mysqld.sock


casino_users table: 

+----+---------------+----------+-------------------------------------------------------------+---------------------+---------------------+
| id | authenticator | username | extra_attributes                                            | created_at          | updated_at          |
+----+---------------+----------+-------------------------------------------------------------+---------------------+---------------------+
|  1 | vijay         | vijay    | NULL                                                        | NULL                | NULL                |
|  2 | static        | testuser | --- !ruby/hash:ActiveSupport::HashWithIndifferentAccess {}
 | 2015-06-29 10:42:36 | 2015-06-29 12:43:32 |
|  3 | vijay1        | vijay123 | --- !ruby/hash:ActiveSupport::HashWithIndifferentAccess     | 2015-06-30 10:42:36 | 2015-06-29 12:46:32 |
|  4 | vijay2        | vijay123 | --- !ruby/hash:ActiveSupport::HashWithIndifferentAccess {}  | 2015-06-30 10:42:36 | 2015-06-29 12:46:32 |
+----+---------------+----------+-------------------------------------------------------------+---------------------+---------------------+
