### ISSUE TITLE
Running CASino via Passenger using relative paths

### ISSUE THREAD

**Issue by skug67** [rbCAS/CASinoApp#16]
I would like to access CASino via [existing_hostname.domain.name]/cas instead via a separate host (e.g. cas.domain.name].  And I seem to be able to log in successfully that way, but at least the initial redirect to "sessions"(and other critical elements of the app, haven't yet tried to figure out how to investigate that) don't prepend the "cas" to the url that they generate.  Any easy way to fix this?

Thanks in advance.

-- Seth Green

**Comment by pencil** [comment]
Running CASino under a non-root URL should actually work without any problems. Maybe the configuration @swobspace posted in issue #51 helps (probably the `PassengerBaseURI` does the trick).

**Comment by skug67** [comment]
Thanks for that hint.  But what I'd gotten running was CASinoApp, which seems to have some problems with absolute URLs embedded someplace (although I can't find it) similar to what was fixed in https://github.com/rbCAS/CASino/commit/12b50732515c27737581b3cad941daa39b5bc882 for the CASino code.  If you could help me figure out how to fix the absolute URL problem in CASinoApp, or alternatively how to run CASino (not App) via Passenger and config.ru, I'd be very grateful.

Thanks again.

-- Seth

**Comment by pencil** [comment]
Please reopen if this is still a problem for you.
