### ISSUE TITLE
Hosting Casino Server App

### ISSUE THREAD

**Issue by fernandohb** [rbCAS/CASinoApp#17]
I followed the instructions on the Casino documentation page, but I can´t get the casino page to work.
I did the implementation directly on the production server and I'm using MySql and LDAP authentication.
An Apache Server is necessary to host the Casino Server?

**Comment by luxflux** [comment]
CASinoApp is a Rails application, you just need a webserver which supports running rack applications. For example Apache with mod_passenger or nginx with the passenger extension.

To help you, we need some more information. Are there any error? How do you determine that it does not work?

**Comment by fernandohb** [comment]
Thanks for the reply, I´m beginner in CAS, Ruby and Rails.
I'm not getting errors, I dont know how to configure apache to host the casino app page.
The casino app documentation doesn't have this configuration. Can you send me a step by step guide, or a link that explains this configuration?
Thanks in advance.

**Comment by luxflux** [comment]
Well, I think the best resource would be [the passenger documentation itself](https://www.phusionpassenger.com/documentation/Users%20guide%20Apache.html#install_on_debian_ubuntu). Let me know if you have any more questions.
