### ISSUE TITLE
different tables for username and password

### ISSUE THREAD

**Issue by edshadi** [rbCAS/CASinoApp#20]
I'm wondering if I can use different tables for username and password columns. My current setup is that they're are in separate tables. I tried aliasing the column, delegating or setting it as a virtual attribute, but that doesn't work. Any pointers?

Thanks

**Comment by pencil** [comment]
You should be able to do that by creating a view directly in your database.

**Comment by edshadi** [comment]
@pencil of course, that makes total sense. Done :)
