### ISSUE TITLE
Question about user creation

### ISSUE THREAD

**Issue by Sylvain** [rbCAS/CASinoApp#3]
Hi Guys! 

First of all, thank you for this awesome work! I'm currently implementing CASinoApp for a project, and it's a joy to work with.

I have a question about user registration. I would like to allow users that are redirected to the casino server to be able to register if they don't have an account yet (and to provide password recovery too). That way, when someone try to login on mywebsite.com, he is redirected to casinoserver.com and if he doesn't have an account, he can create one and then be redirected to mywebsite.com as a logged in user. 

I was wondering about the best way to do that : 
1. Integrate Devise into CASinoApp and mix the user creation and autorisation
2. Create a separate Rails app for that. In that case, I don't know how to be signed-in into the CASino server after user registration. 

I'll be very glad about any tip or recommandation or link. I haven't found resource to help tackle this.

Many thanks by advance.

**Comment by diegobernardes** [comment]
In my app CASino is working with devise, there is a nice post about this here: http://bentoncreation.com/post/74392403766/devise-cas-using-devise-cas-authenticatable-and

So far, so good. CASino respect my authentication logic, not only "email" and "password" and handle the logins. Devise in the other side do all the other stuffs like recover password, account activation, etc.. etc..

The only thing i need to do now is integrate with omniauth :smile:

**Comment by sunilkalyan08** [comment]
If user creation and password management handled in separate application. How to connect the client app with user creation application along with server

**Comment by pencil** [comment]
What do you mean by "connect"?
